/*jslint node: true */
/*jslint esnext: true*/
"use strict";

module.exports = {
    ACTION_TYPES: {
        POLYGON_ADDED_ACTION: 'POLYGON_ADDED_ACTION',
        POLYGON_CHANGED_ACTION: 'POLYGON_CHANGED_ACTION',
        POLYGON_SELF_DESTRUCT: 'POLYGON_SELF_DESTRUCT',
        MARKERS_ADDED_ACTION: 'MARKERS_ADDED_ACTION'
    },
    UPDATE_TYPES: {
        TURF_CHANGED: 'TURF_CHANGED',
        POLYGON_CHANGED: 'POLYGON_CHANGED',
        POLYGON_ADDED: 'POLYGON_ADDED',
        POLYGON_DESTROYED: 'POLYGON_DESTROYED',
        MARKERS_ADDED: 'MARKERS_ADDED'
    }
};
